/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.sw;

import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Noor
 */
public class count_max_min extends javax.swing.JFrame {
    
   private final String url = "jdbc:sqlserver://localhost\\SQLEXPRESS;"
        + "databaseName=CollegeAdmission;"
        + "user=sa;password=12345;"
        + "trustServerCertificate=true;";

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(count_max_min.class.getName());

    /**
     * Creates new form count_max_min
     */
    public count_max_min() {
        initComponents();
        
          try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Cannot Load JDBC Driver !!!!");
        }
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Count_btn = new javax.swing.JButton();
        Max_btn = new javax.swing.JButton();
        Min_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 153));

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        Count_btn.setBackground(new java.awt.Color(255, 255, 255));
        Count_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Count_btn.setForeground(new java.awt.Color(0, 0, 0));
        Count_btn.setText("Count_Student");
        Count_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Count_btnActionPerformed(evt);
            }
        });

        Max_btn.setBackground(new java.awt.Color(255, 255, 255));
        Max_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Max_btn.setForeground(new java.awt.Color(0, 0, 0));
        Max_btn.setText("Max_Major");
        Max_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Max_btnActionPerformed(evt);
            }
        });

        Min_btn.setBackground(new java.awt.Color(255, 255, 255));
        Min_btn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Min_btn.setForeground(new java.awt.Color(0, 0, 0));
        Min_btn.setText("Min_Major");
        Min_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Min_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Max_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Min_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Count_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap(184, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(Count_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(Max_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(Min_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Count_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Count_btnActionPerformed
   Connection con = null;
        Statement stmt = null;
        ResultSet result = null;

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            String query = "SELECT COUNT(*) as student_count FROM Students";
            result = stmt.executeQuery(query);

            if (result.next()) {
                JOptionPane.showMessageDialog(this,
                    "Count = " + result.getInt("student_count"));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            if (con != null)   { try { con.close();    } catch (Exception ex) {} }
            if (stmt != null)  { try { stmt.close();   } catch (Exception ex) {} }
            if (result != null){ try { result.close(); } catch (Exception ex) {} }
        }


    }//GEN-LAST:event_Count_btnActionPerformed

    private void Max_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Max_btnActionPerformed
  Connection con = null;
        Statement stmt = null;
        ResultSet result = null;

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            
        
            String query = "SELECT TOP 1 Major, COUNT(*) as num FROM Students GROUP BY Major ORDER BY num DESC";

            
            result = stmt.executeQuery(query);

            if (result.next()) {
    
                JOptionPane.showMessageDialog(this,
        
                        "أكتر قسم: " + result.getString("Major") + " (" + result.getInt("num") + " طالب)");
}
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            if (con != null)   { try { con.close();    } catch (Exception ex) {} }
            if (stmt != null)  { try { stmt.close();   } catch (Exception ex) {} }
            if (result != null){ try { result.close(); } catch (Exception ex) {} }
        }

    }//GEN-LAST:event_Max_btnActionPerformed

    private void Min_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Min_btnActionPerformed
        
        Connection con = null;
        Statement stmt = null;
        ResultSet result = null;

        try {
            con = DriverManager.getConnection(url);
            stmt = con.createStatement();
            
            String query = "SELECT TOP 1 Major, COUNT(*) as num FROM Students GROUP BY Major ORDER BY num ASC";

            result = stmt.executeQuery(query);

            if (result.next()) {
    
                JOptionPane.showMessageDialog(this,
        
                        "أقل قسم: " + result.getString("Major") + " (" + result.getInt("num") + " طالب)");
}
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } finally {
            if (con != null)   { try { con.close();    } catch (Exception ex) {} }
            if (stmt != null)  { try { stmt.close();   } catch (Exception ex) {} }
            if (result != null){ try { result.close(); } catch (Exception ex) {} }
        } 
        
    }//GEN-LAST:event_Min_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new count_max_min().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Count_btn;
    private javax.swing.JButton Max_btn;
    private javax.swing.JButton Min_btn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
