/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.sw;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.sql.*;
/**
 *
 * @author 𝓨𝓪𝓼𝓼𝓶𝓲𝓷_'
 */
public class registration extends javax.swing.JFrame {
    public registration() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblFirstName = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblMajor = new javax.swing.JLabel();
        lblGpa = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        txtMajor = new javax.swing.JTextField();
        lblGpa1 = new javax.swing.JLabel();
        userpassword_txt = new javax.swing.JPasswordField();
        male = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));
        jPanel2.setLayout(null);

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sw/icons8-registration-24.png"))); // NOI18N
        lblTitle.setText("Registration");
        lblTitle.setOpaque(true);
        jPanel2.add(lblTitle);
        lblTitle.setBounds(90, 10, 200, 30);

        lblId.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setText("National ID:");
        jPanel2.add(lblId);
        lblId.setBounds(30, 150, 80, 25);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId);
        txtId.setBounds(130, 150, 200, 25);

        lblFirstName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name:");
        jPanel2.add(lblFirstName);
        lblFirstName.setBounds(30, 70, 80, 25);
        jPanel2.add(txtFirstName);
        txtFirstName.setBounds(130, 70, 200, 25);

        lblLastName.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name:");
        jPanel2.add(lblLastName);
        lblLastName.setBounds(30, 110, 80, 25);
        jPanel2.add(txtLastName);
        txtLastName.setBounds(130, 110, 200, 25);

        lblMajor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblMajor.setForeground(new java.awt.Color(255, 255, 255));
        lblMajor.setText("Password  :");
        jPanel2.add(lblMajor);
        lblMajor.setBounds(30, 190, 80, 25);

        lblGpa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblGpa.setForeground(new java.awt.Color(255, 255, 255));
        lblGpa.setText("Gender");
        jPanel2.add(lblGpa);
        lblGpa.setBounds(30, 270, 80, 25);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/sw/login_24dp_1F1F1F_FILL1_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnAdd.setText("Submit");
        btnAdd.setOpaque(true);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdd);
        btnAdd.setBounds(150, 310, 110, 35);

        txtMajor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMajorActionPerformed(evt);
            }
        });
        jPanel2.add(txtMajor);
        txtMajor.setBounds(130, 230, 200, 25);

        lblGpa1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lblGpa1.setForeground(new java.awt.Color(255, 255, 255));
        lblGpa1.setText("Major:");
        jPanel2.add(lblGpa1);
        lblGpa1.setBounds(30, 230, 80, 25);

        userpassword_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassword_txtActionPerformed(evt);
            }
        });
        jPanel2.add(userpassword_txt);
        userpassword_txt.setBounds(130, 190, 200, 25);

        male.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        male.setText("male");
        male.setOpaque(true);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel2.add(male);
        male.setBounds(130, 270, 80, 22);

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jRadioButton2.setText("female");
        jRadioButton2.setOpaque(true);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton2);
        jRadioButton2.setBounds(250, 270, 90, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String gender = "";

    if (male.isSelected()) {

        gender = "Male";

    } else if (jRadioButton2.isSelected()) {

        gender = "Female";
    }

    String password =
            new String(userpassword_txt.getPassword());
     // VALIDATION
    if(txtFirstName.getText().trim().isEmpty() ||
       txtLastName.getText().trim().isEmpty() ||
       txtId.getText().trim().isEmpty() ||
       txtMajor.getText().trim().isEmpty() ||
       password.trim().isEmpty()){

        JOptionPane.showMessageDialog(this,
                "Please fill all fields");
        return;
    }
    
    
    try {

    Connection con =
            DatabaseConnection.getConnection();

    String checkQuery =
    "SELECT * FROM Students WHERE NationalID = ?";

    PreparedStatement ps =
            con.prepareStatement(checkQuery);

    ps.setString(1, txtId.getText());

    ResultSet rs = ps.executeQuery();

    if(rs.next()){

        JOptionPane.showMessageDialog(this,
                "National ID already exists");

        return;
    }

    } catch (Exception e) {

    JOptionPane.showMessageDialog(this,
            e.getMessage());

    return;
    }


    Student s = new Student(

            txtFirstName.getText(),
            txtLastName.getText(),
            txtId.getText(),
            password,
            gender,
            txtMajor.getText()

    );

    StudentDAO dao = new StudentDAO();

    if (dao.addStudent(s)) {

        JOptionPane.showMessageDialog(this,
                "Registration Successful!");

        txtFirstName.setText("");
        txtLastName.setText("");
        txtId.setText("");
        txtMajor.setText("");
        userpassword_txt.setText("");

        buttonGroup1.clearSelection();

    } else {

        JOptionPane.showMessageDialog(this,
                "Registration Failed!");
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtMajorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMajorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMajorActionPerformed

    private void userpassword_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassword_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpassword_txtActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblGpa;
    private javax.swing.JLabel lblGpa1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JPasswordField userpassword_txt;
    // End of variables declaration//GEN-END:variables
}
